import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI PC
 */
public class Giris extends javax.swing.JFrame {

    /**
     * Creates new form Giris
     */
    public Giris() {
        initComponents();
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
            simge_durumu.setBorder(border);
            kapat.setBorder(border);
            
            kullanici_adi.setBorder(border);
            sifre.setBorder(border);
            this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        simge_durumu = new javax.swing.JLabel();
        kapat = new javax.swing.JLabel();
        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        giris_yap = new javax.swing.JButton();
        iconA = new javax.swing.JLabel();
        iconB = new javax.swing.JLabel();
        kayda_gec = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-1340526_1920.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simge_durumu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        simge_durumu.setText("-");
        simge_durumu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simge_durumuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simge_durumuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simge_durumuMouseExited(evt);
            }
        });
        getContentPane().add(simge_durumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 11, -1, -1));

        kapat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        kapat.setText("X");
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapatMouseExited(evt);
            }
        });
        getContentPane().add(kapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 11, -1, -1));

        kullanici_adi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kullanici_adi.setForeground(new java.awt.Color(204, 204, 204));
        kullanici_adi.setText("kullanıcı adı");
        kullanici_adi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kullanici_adiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                kullanici_adiFocusLost(evt);
            }
        });
        getContentPane().add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 143, 190, -1));

        sifre.setForeground(new java.awt.Color(204, 204, 204));
        sifre.setText("şifre alanı");
        sifre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sifreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sifreFocusLost(evt);
            }
        });
        getContentPane().add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 184, 190, -1));

        giris_yap.setBackground(new java.awt.Color(0, 87, 135));
        giris_yap.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        giris_yap.setText("Giriş Yap");
        giris_yap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                giris_yapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                giris_yapMouseExited(evt);
            }
        });
        giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giris_yapActionPerformed(evt);
            }
        });
        getContentPane().add(giris_yap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 222, 190, -1));

        iconA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kullanici.png"))); // NOI18N
        iconA.setText("jLabel4");
        getContentPane().add(iconA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 30, 30));

        iconB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sifre.png"))); // NOI18N
        getContentPane().add(iconB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 184, 30, 30));

        kayda_gec.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        kayda_gec.setForeground(new java.awt.Color(0, 51, 255));
        kayda_gec.setText("-Kayıtlı değil misiniz ? Kayıt Olun-");
        kayda_gec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayda_gecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kayda_gecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kayda_gecMouseExited(evt);
            }
        });
        getContentPane().add(kayda_gec, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 277, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-1340526_1920.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simge_durumuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseEntered
Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    simge_durumu.setBorder(border);
    simge_durumu.setForeground(Color.white);
    }//GEN-LAST:event_simge_durumuMouseEntered

    private void simge_durumuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseExited
Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
    simge_durumu.setBorder(border);
    simge_durumu.setForeground(Color.black);
    
    }//GEN-LAST:event_simge_durumuMouseExited

    private void kapatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseEntered
Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    kapat.setBorder(border);
    kapat.setForeground(Color.white);
    }//GEN-LAST:event_kapatMouseEntered

    private void kapatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseExited
Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
    kapat.setBorder(border);
    kapat.setForeground(Color.black);
    }//GEN-LAST:event_kapatMouseExited

    private void simge_durumuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_simge_durumuMouseClicked

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
       System.exit(0);
    }//GEN-LAST:event_kapatMouseClicked

    private void kullanici_adiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kullanici_adiFocusGained
     if(kullanici_adi.getText().toLowerCase().equals("kullanıcı adı")){
            kullanici_adi.setText("");
            kullanici_adi.setForeground(Color.black);

     }
      Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
    iconA.setBorder(border);
    }//GEN-LAST:event_kullanici_adiFocusGained

    private void kullanici_adiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kullanici_adiFocusLost
      if(kullanici_adi.getText().equals("")|| kullanici_adi.getText().toLowerCase().equals("kullanıcı adı")){
          kullanici_adi.setText("kullanıcı adı");
          kullanici_adi.setForeground(new Color(204,204,204));
          
      }
      iconA.setBorder(null);
    }//GEN-LAST:event_kullanici_adiFocusLost

    private void sifreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreFocusGained
   String sifreA=String.valueOf(sifre.getPassword());
    if(sifreA.toLowerCase().equals("şifre alanı")){
      sifre.setText("");
      sifre.setForeground(Color.black);
    }
    Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        iconB.setBorder(border);
    }//GEN-LAST:event_sifreFocusGained

    private void sifreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sifreFocusLost
        String sifreA=String.valueOf(sifre.getPassword());
    if(sifreA.equals("")|| sifreA.toLowerCase().equals("şifre alanı")){
        sifre.setText("şifre alanı");
        sifre.setForeground(new Color(204,204,204));
    }
    iconB.setBorder(null);
    }//GEN-LAST:event_sifreFocusLost

    private void giris_yapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giris_yapMouseEntered
        giris_yap.setBackground(new Color(0,100,200));
    }//GEN-LAST:event_giris_yapMouseEntered

    private void giris_yapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giris_yapMouseExited
       giris_yap.setBackground(new Color(0,87,135));
    }//GEN-LAST:event_giris_yapMouseExited

    private void giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giris_yapActionPerformed
    String kullaniciA=kullanici_adi.getText();
    String sifreA=String.valueOf(sifre.getPassword());
        PreparedStatement st;
        ResultSet rs;
    String sorgu="SELECT * FROM uyeler WHERE kullanici_adi = ? AND sifre = ?";
        if(kullaniciA.trim().equals("kullanıcı adı")){
JOptionPane.showMessageDialog(null, "Kullanıcı Adınızı Giriniz","Kullanıcı Adı Alanı Boş",2);
        }
        else if(sifreA.trim().equals("şifre alanı")){
JOptionPane.showMessageDialog(null, "Şifrenizi Giriniz","Şifre Alanı Boş",2);           
        }
        else {
        try {
            st=VeritabaniBaglantisi.getConnection().prepareStatement(sorgu);
                st.setString(1, kullaniciA);
                st.setString(2, sifreA);
                    rs=st.executeQuery();
            if(rs.next()){
JOptionPane.showMessageDialog(null, "Kullanıcı adı ve şifre doğru sisteme giriş yapılıyor");    
Thread.sleep(3000); 
System.exit(0);

            } 
            else {
JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre yanlış","Hatalı Giriş",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_giris_yapActionPerformed

    private void kayda_gecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseEntered
Border border=BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
    kayda_gec.setBorder(border);
    }//GEN-LAST:event_kayda_gecMouseEntered

    private void kayda_gecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseExited
      kayda_gec.setBorder(null);
    }//GEN-LAST:event_kayda_gecMouseExited

    private void kayda_gecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayda_gecMouseClicked
      Kayit kayit=new Kayit();
        setVisible(false);
        kayit.setVisible(true);
    }//GEN-LAST:event_kayda_gecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giris_yap;
    private javax.swing.JLabel iconA;
    private javax.swing.JLabel iconB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel kapat;
    private javax.swing.JLabel kayda_gec;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JLabel simge_durumu;
    // End of variables declaration//GEN-END:variables
}
