import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MSI PC
 */
public class Kayit extends javax.swing.JFrame {

    /**
     * Creates new form Kayit
     */
    public Kayit() {
        initComponents();
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
            simge_durumu.setBorder(border);
            kapat.setBorder(border);
Border borderA=BorderFactory.createMatteBorder(1, 4, 1, 1, Color.white);  
        ad.setBorder(borderA);
        soyad.setBorder(borderA);
        kullanici_adi.setBorder(borderA);
        sifre.setBorder(borderA);
        sifre_onay.setBorder(borderA);
        telefon_no.setBorder(borderA);
ButtonGroup bg=new ButtonGroup();
    bg.add(erkek);
    bg.add(kadin);
    bg.add(diger);
    this.setLocationRelativeTo(null);
    }
    
boolean kontrol_et(){
    String adA=ad.getText();
    String soyadA=soyad.getText();
    String kullanici_adiA=kullanici_adi.getText();
    String sifreA=String.valueOf(sifre.getPassword());
    String sifreAA=String.valueOf(sifre_onay.getPassword());
    String telefon_noA=telefon_no.getText();
if(adA.trim().equals("") || soyadA.trim().equals("") || kullanici_adiA.trim().equals("")
|| sifreA.trim().equals("") || sifreAA.trim().equals("") || telefon_noA.trim().equals("")){
    JOptionPane.showMessageDialog(null, "Herhangi bir alan boş bırakılamaz","Hatalı İşlem",2);
    return false;
}   
else if(!sifreA.equals(sifreAA)){
    JOptionPane.showMessageDialog(null, "Şifreler eşleşmiyor","Şifre Onayı",2);
    return false;
}
    return true;
}
boolean kullanici_adini_kontrol_et(String kullanici_adi){
    boolean kullanici_adi_varligi=false;
    PreparedStatement st;
    ResultSet rs;
String sorgu="SELECT * FROM uyeler WHERE kullanici_adi= ?";
    try {
        st=VeritabaniBaglantisi.getConnection().prepareStatement(sorgu);
        st.setString(1, kullanici_adi);
        rs=st.executeQuery();
            if(rs.next()){
                kullanici_adi_varligi=true;
JOptionPane.showMessageDialog(null, "Bu kullanıcı adı alınmış.Başka bir kullanıcı"
        + " adı deneyin","Kullanıcı Adı Hatası",2);
        this.kullanici_adi.setText("");
            }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return kullanici_adi_varligi;
}
String gorsel_yolu=null;
public ImageIcon ResizeImageIcon(String gorsel_yolu,byte [] gorsel){
    ImageIcon imageA=null;
        if(gorsel_yolu!=null){
                imageA=new ImageIcon(gorsel_yolu);
        }
        else{
            imageA=new ImageIcon(gorsel);
        }
        Image img=imageA.getImage();
        Image img2=img.getScaledInstance(gorselA.getWidth(),gorselA.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon imageB=new ImageIcon(img2);
            return  imageB;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simge_durumu = new javax.swing.JLabel();
        kapat = new javax.swing.JLabel();
        kaydol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gorselA = new javax.swing.JLabel();
        fotograf_ekle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        kullanici_adi = new javax.swing.JTextField();
        sifre_onay = new javax.swing.JPasswordField();
        telefon_no = new javax.swing.JTextField();
        erkek = new javax.swing.JRadioButton();
        kadin = new javax.swing.JRadioButton();
        diger = new javax.swing.JRadioButton();
        kayit_mevcut = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simge_durumu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        simge_durumu.setText("-");
        simge_durumu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simge_durumuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simge_durumuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simge_durumuMouseExited(evt);
            }
        });
        getContentPane().add(simge_durumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 11, -1, -1));

        kapat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        kapat.setText("X");
        kapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kapatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kapatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kapatMouseExited(evt);
            }
        });
        getContentPane().add(kapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 11, -1, -1));

        kaydol.setBackground(new java.awt.Color(0, 87, 135));
        kaydol.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        kaydol.setText("Kaydol");
        kaydol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kaydolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kaydolMouseExited(evt);
            }
        });
        kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolActionPerformed(evt);
            }
        });
        getContentPane().add(kaydol, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 476, 200, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Hesap Fotoğrafı:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(gorselA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1, 129, 180));

        fotograf_ekle.setBackground(new java.awt.Color(0, 87, 135));
        fotograf_ekle.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        fotograf_ekle.setText("Fotoğraf Ekle");
        fotograf_ekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fotograf_ekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fotograf_ekleMouseExited(evt);
            }
        });
        fotograf_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotograf_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(fotograf_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 129, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Adınız:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 241, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Soyadınız:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Kullanıcı Adınız:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 299, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Şifre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 328, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Şifrenizi Onaylayın:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 357, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Telefon No:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 386, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Cinsiyet:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 415, -1, -1));

        ad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 241, 200, -1));

        soyad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 270, 200, -1));

        sifre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 328, 200, -1));

        kullanici_adi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(kullanici_adi, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 299, 200, -1));

        sifre_onay.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(sifre_onay, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 357, 200, -1));

        telefon_no.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        telefon_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefon_noKeyTyped(evt);
            }
        });
        getContentPane().add(telefon_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 386, 200, -1));

        erkek.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        erkek.setSelected(true);
        erkek.setText("Erkek");
        getContentPane().add(erkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 414, -1, -1));

        kadin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kadin.setText("Kadın");
        getContentPane().add(kadin, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 414, -1, -1));

        diger.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        diger.setText("Diğer");
        getContentPane().add(diger, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 414, -1, -1));

        kayit_mevcut.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        kayit_mevcut.setForeground(new java.awt.Color(0, 51, 255));
        kayit_mevcut.setText("-Zaten kayıtlı mısın ? Giriş Yap-");
        kayit_mevcut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kayit_mevcutMouseExited(evt);
            }
        });
        getContentPane().add(kayit_mevcut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-1340526_1920.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simge_durumuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_simge_durumuMouseClicked

    private void simge_durumuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseEntered
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        simge_durumu.setBorder(border);
        simge_durumu.setForeground(Color.white);
    }//GEN-LAST:event_simge_durumuMouseEntered

    private void simge_durumuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simge_durumuMouseExited
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        simge_durumu.setBorder(border);
        simge_durumu.setForeground(Color.black);

    }//GEN-LAST:event_simge_durumuMouseExited

    private void kapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_kapatMouseClicked

    private void kapatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseEntered
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        kapat.setBorder(border);
        kapat.setForeground(Color.white);
    }//GEN-LAST:event_kapatMouseEntered

    private void kapatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kapatMouseExited
        Border border=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        kapat.setBorder(border);
        kapat.setForeground(Color.black);
    }//GEN-LAST:event_kapatMouseExited

    private void kaydolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydolMouseEntered
        kaydol.setBackground(new Color(0,100,200));
    }//GEN-LAST:event_kaydolMouseEntered

    private void kaydolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kaydolMouseExited
        kaydol.setBackground(new Color(0,87,135));
    }//GEN-LAST:event_kaydolMouseExited

    private void kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolActionPerformed
 String adA=ad.getText();
 String soyadA=soyad.getText();
 String telefon_noA=telefon_no.getText();
    String cinsiyetA="Erkek";
        if(kadin.isSelected()){
            cinsiyetA="Kadin";
            
        }
        else if(diger.isSelected()){
            cinsiyetA="Diger";
        }
  String kullanici_adiA=kullanici_adi.getText();
  String sifreA=String.valueOf(sifre.getPassword());
  String sifreAA=String.valueOf(sifre.getPassword());
    if(kontrol_et())
        if(!kullanici_adini_kontrol_et(kullanici_adiA)){
            PreparedStatement st;
            ResultSet rs;
String sorgu="INSERT INTO `uyeler`(`adi`, `soyadi`, `telefon_numarasi`, `cinsiyeti`, `hesap_fotografi`, `kullanici_adi`, `sifre`) VALUES (?,?,?,?,?,?,?)";
            try {
                st=VeritabaniBaglantisi.getConnection().prepareStatement(sorgu);
                st.setString(1, adA);
                st.setString(2, soyadA);
                st.setString(3, telefon_noA);
                st.setString(4, cinsiyetA);
                    if(gorsel_yolu!=null){
                        InputStream gorsel=new FileInputStream(new File(gorsel_yolu));
                            st.setBlob(5, gorsel);
                            
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Fotoğraf seçilmedi","Uyarı",1);
                        st.setNull(5, java.sql.Types.NULL);
                    }
                st.setString(6,kullanici_adiA);
                st.setString(7, sifreA);
                    if(st.executeUpdate()!=0){
                        JOptionPane.showMessageDialog(null, "Hesap Oluşturuldu");
                        Giris giris=new Giris();
                        setVisible(false);
                        giris.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Hata:Hesap Oluşturulmadı");
                    }
                
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_kaydolActionPerformed

    private void fotograf_ekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotograf_ekleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_fotograf_ekleMouseEntered

    private void fotograf_ekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fotograf_ekleMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_fotograf_ekleMouseExited

    private void fotograf_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotograf_ekleActionPerformed
   JFileChooser file=new JFileChooser();
    file.setCurrentDirectory(new File("user.home"));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.images", "jpg","png");
            file.addChoosableFileFilter(filter);
            int sonuc=file.showSaveDialog(null);  
                if(sonuc==JFileChooser.APPROVE_OPTION){
                    File secilen_gorsel=file.getSelectedFile();
                    String gorsel_yoluA=secilen_gorsel.getAbsolutePath();
                            gorselA.setIcon(ResizeImageIcon(gorsel_yoluA, null));
                            gorsel_yolu=gorsel_yoluA;
                }
                else {
                    JOptionPane.showMessageDialog(null,"Dosya Seçilmedi","Dosya Hatası",2);
                }
    }//GEN-LAST:event_fotograf_ekleActionPerformed

    private void telefon_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefon_noKeyTyped
            if(!Character.isDigit(evt.getKeyChar())){
                evt.consume();
            }
    }//GEN-LAST:event_telefon_noKeyTyped

    private void kayit_mevcutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseClicked
        Giris giris=new Giris();
            setVisible(false);
            giris.setVisible(true);
    }//GEN-LAST:event_kayit_mevcutMouseClicked

    private void kayit_mevcutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseEntered
        Border border=BorderFactory.createMatteBorder(0, 0, 1, 0, Color.blue);
        kayit_mevcut.setBorder(border);
    }//GEN-LAST:event_kayit_mevcutMouseEntered

    private void kayit_mevcutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_mevcutMouseExited
        kayit_mevcut.setBorder(null);
    }//GEN-LAST:event_kayit_mevcutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JRadioButton diger;
    private javax.swing.JRadioButton erkek;
    private javax.swing.JButton fotograf_ekle;
    private javax.swing.JLabel gorselA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton kadin;
    private javax.swing.JLabel kapat;
    private javax.swing.JButton kaydol;
    private javax.swing.JLabel kayit_mevcut;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JPasswordField sifre_onay;
    private javax.swing.JLabel simge_durumu;
    private javax.swing.JTextField soyad;
    private javax.swing.JTextField telefon_no;
    // End of variables declaration//GEN-END:variables
}
